version: 2.1

working_directory: ~/code

environment:
  # Customize the JVM maximum heap limit
  JVM_OPTS: -Xmx3200m
  TERM: dumb

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: cd ./example/android/ && sudo chmod +x ./gradlew && ./gradlew androidDependencies
      - run:
          name: Build
          command: cd ./example/android/ && sudo chmod +x ./gradlew && ./gradlew assembleDebug
